name: CI

on:
    push:
      tags:
        - 'v*'

jobs:  
  build:
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v4

      - name: init
        run: |
            echo Hey Man!
            mkdir -p /tmp/hey
            echo "Hey from the temp dir" > /tmp/hey/hey.txt
    
      - name: another_init
        run: |
            echo Another
            echo "Another file" > /tmp/hey/another.txt
    
      - name: Yet_another_init
        run: |
            echo Yet Another
            echo "Yet Another file" > /tmp/hey/yet_another.txt
      
      - name: Upload a file
        uses: actions/upload-artifact@v4
        with:
            name: My artifact
            path: /tmp/hey/
