name: CI

on:
    push:
      tags:
        - 'v*'

jobs:  
  build:
      strategy:
        matrix:
          include:
          - host: riscv32im-linux-x86_64
            runs-on: ubuntu-22.04
            arch: x86_64

          - host: riscv32im-linux-arm64
            runs-on: ubuntu-22.04-arm64
            arch: arm64

          - host: riscv64im-linux-x86_64
            runs-on: ubuntu-22.04
            arch: x86_64

          - host: riscv64im-linux-arm64
            runs-on: ubuntu-22.04-arm64
            arch: arm64

          - host: riscv32im-osx-arm64
            runs-on: macos-14
            arch: arm64

          - host: riscv32im-osx-x86_64
            runs-on: macos-12
            arch: x86_64

          - host: riscv64im-osx-arm64
            runs-on: macos-14
            arch: arm64

          - host: riscv64im-osx-x86_64
            runs-on: macos-12
            arch: x86_64

      runs-on: ${{ matrix.runs-on }}

      steps:      
        - uses: actions/checkout@v4

        - name: init
          run: |
              echo uname -a
              mkdir -p /tmp/hey
              echo "I am host> ${{ matrix.host }} and I have arch ${{ matrix.arch }} " > /tmp/hey/${{ matrix.host }}.txt
        
        - name: Upload a file
          uses: actions/upload-artifact@v4
          with:
              name: ${{ matrix.host }}.txt
              path: /tmp/hey/${{ matrix.host }}.txt
