name: CI

on:  
  push:
    branches: [ "bro" ]

jobs:  
  build:
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v4

      - name: init
        run: |
            echo Hey Man!
            mkdir -p /tmp/hey
            echo "Hey from the temp dir" > /tmp/hey/hey.txt
      
      - name: Upload a file
        uses: actions/upload-artifact@v4
        with:
            name: my-artifact
            path: /tmp/hey/hey.txt
